### ISSUE TITLE
Scale for map screenshots

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-lab-exports#23]
Putting this here because I don't imagine it would go in the actual image, but currently we don't have a plan for showing the scale of the choropleth and bubble in the map screenshots. This may not be as much of an issue if we're including all of the data in the last slide, but raising it just in case

**Comment by pjsier** [comment]
@james-minton wanted to flag this for you. We need some way of factoring the legends into the export design

**Comment by james-minton** [comment]
@pjsier Is this bubble + chloro or just the latter?

**Comment by pjsier** [comment]
Ideally both, so it's related to https://github.com/EvictionLab/eviction-maps/issues/568
