### ISSUE TITLE
Map screenshot for PowerPoint

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-lab-exports#4]
Not sure if we'll be able to do this reasonably, but the original research PowerPoint template includes a choropleth map of the selected map feature. This gets unreasonably complicated for multiple reasons, but I'm including options we've looked at here.

* Generate a screenshot of the map with [`preserveDrawingBuffer`](https://stackoverflow.com/questions/42483449/mapbox-gl-js-export-map-to-png-or-pdf)
    * This won't work on Lambda because, even when using Chromeless, Lambdas don't have GPUs and can't render WebGL directly
* Pre-render raster image tiles, stitch them together for export with [abaculus](https://github.com/mapbox/abaculus)
    * Would have to pre-render for every single year of data, which quickly gets out of hand
* Render an image using `node-mapnik`, a Mapnik XML file, and [abaculus](https://github.com/mapbox/abaculus)
    * Probably the most likely option, but we'll need to figure out how to get an executable file for the image rendering on the Lambda. An example of this is [serverless-sharp-image](https://github.com/adieuadieu/serverless-sharp-image)

**Comment by Lane** [comment]
I've been thinking about this a bit more. To get around the no GPU issues on Lambda, could we have a Lambda function that submits an AWS Batch job using our own custom docker image in ECR?  I'm not sure how quick AWS Batch is to spin up, but if we're able to get the spin up times low enough with caching or something, it might be worth looking at?

**Comment by pjsier** [comment]
Batch is really slow, and generally for larger, long-running tasks, so the workflow is emailing people the files a few minutes later it's not really an option. I'm not sure if there are other AWS services we could spin up faster though, but I feel like there could be something that would work
